branch-defaults:
  refactor-pipeline:
    environment: api-ecordel
deploy:
  artifact: target/server.jar
environment-defaults:
  api-ecordel:
    branch: null
    repository: null
global:
  application_name: api-ecordel
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
