app:
  xilogravura.path: "./"
  ai.review:
    # mustache template for the prompt to send to the AI for reviewing the cordel text
    userPrompt: |-
      Reveja o texto do cordel
      {{#title}}
        - Título: {{{title}}}
      {{/title}}
      {{#author}}
        - Autor: {{{name}}}
      {{/author}}
      {{#year}}
        - Ano provável de publicação: {{{year}}}
      {{/year}}
      {{#source}}
        - Fonte: {{{source}}}
      {{/source}}
      Texto:
      {{#content}}
      {{{content}}}
      {{/content}}

    systemPrompt: |-
      Você é um especialista em revisão de literatura de cordel brasileira.
      O texto enviado para revisão pode ter sido extraído por OCR e pode conter erros de digitação,
      acentuação incorreta, palavras quebradas e pequenos ruídos. O texto é organizado em estrofes e versos, e você deve manter essa estrutura.
      Cada estrofe é separada por uma linha em branco, e cada verso é separado por uma quebra de linha.
    
      Você deve seguir as seguintes regras ao revisar o texto:
      - Corrigir erros de OCR e ortografia.
      - Ajustar estrofes para manter a estrutura original do cordel.
      - Juntar versos se necessário, mas sem criar novos versos ou estrofes.
      - Remover caracteres estranhos e ruídos, mantendo a essência do texto.
      - Preservar estilo, ritmo, rima e organização em estrofes.
      - Não reescrever o texto para "modernizar".
      - Responder somente com o texto revisado.

# discuss how to versioning the api for now it will be static
server.servlet.context-path: "/api/v1"

cache:
  maximum-size: 1000
  ttl-in-minutes: 10

ftp:
  server: ftp.turismonocariri.com.br
  port: 21
  user: user
  password: pass
  baseUrl: "http://xilos.ecordel.com.br/"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: username
    password: password

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: none

server.port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

resilience4j.ratelimiter:
  instances:
    default:
      limitForPeriod: 50
      limitRefreshPeriod: 500ms
      timeoutDuration: 0ms        # Fail immediately if limit reached
      registerHealthIndicator: true

logging:
  level:
    root: INFO